packages:
  - "."

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@types/node@24.13.5"
  - tsx@4.23.14
